"""
TEMPORARY (Phase 2 fallback): trains a RandomForestClassifier on the
SYNTHETIC dataset generated by datasets/generate_synthetic_dataset.py.

This produces a real, working model file — but trained on synthetic
data, not real labeled malware samples. Replace with a model trained
on real data (CIC-AndMal, Drebin, etc.) once available.
"""

from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

DATASET_FILE = Path(__file__).resolve().parent / "datasets" / "synthetic_features.csv"
MODEL_OUTPUT = Path(__file__).resolve().parent.parent / "models" / "spyware_classifier.joblib"


def load_dataset() -> tuple:
    """Load the synthetic dataset and split into features (X) and labels (y)."""
    df = pd.read_csv(DATASET_FILE)
    X = df.drop(columns=["label"])
    y = df["label"]
    return X, y


def train_model(X, y) -> RandomForestClassifier:
    """Train a RandomForestClassifier and print a quick evaluation."""
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    print(f"Accuracy on held-out synthetic test set: {accuracy_score(y_test, predictions):.2f}")
    print(classification_report(y_test, predictions))

    return model


def save_model(model) -> None:
    """Save the trained model to disk with joblib."""
    MODEL_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, MODEL_OUTPUT)
    print(f"Model saved to {MODEL_OUTPUT}")


def main():
    X, y = load_dataset()
    model = train_model(X, y)
    save_model(model)


if __name__ == "__main__":
    main()